// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kingsmen.Domain.Entities
{
    public partial class Client : Entity
    {
        public Client()
        {
        }

        public string Name { get; set; }
        public string ClientPrefix { get; set; }
    }
}