// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Kingsmen.Domain.Entities
{
    public partial class Role : Entity
    {
        public Role() { }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<RoleFunctionalAbility> RoleFunctionalAbilities { get; set; }
        public List<UserRole> UserRoles { get; set; }
    }
}