// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Kingsmen.Domain.Entities
{
    public partial class User : Entity
    {
        public User()
        {

        }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }

        public List<UserRole> UserRoles { get; set; }

        public override bool Equals(object obj)
        {
            if (obj.GetType() != typeof(User)) return false;

            User testUsr = (User)obj;

            return this.GetHashCode() == testUsr.GetHashCode();
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(FirstName, LastName, IsActive, Email);
        }
    }
}
