name: Eslint
on: 
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
       npm install
       npm -g i eslint-cli
       npm i eslint --save-dev
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx