name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        
        - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

        - run: |
          make bootstrap
          make release

        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v2
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.